version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vending-machine-app
    container_name: vending-machine-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - vending-machine-network

  db:
    image: mysql:8.0
    container_name: vending-machine-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vending_machine_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - vending-machine-network

  web:
    image: nginx:alpine
    container_name: vending-machine-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vending-machine-network

networks:
  vending-machine-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
